name: Renovate

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]
    paths: [.github/workflows/renovate.yaml]
  schedule:
  - cron: '0 */12 * * *'
  workflow_dispatch:
  workflow_call:
    inputs:
      RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS:
        description: "A list of regular expressions that decide which commands in postUpgradeTasks are allowed to run. If this list is empty then no tasks will be executed."
        required: false
        default: ""
        type: string
      LOG_LEVEL:
        description: "Log level"
        required: false
        default: "info"
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=docker depName=renovate/renovate versioning=docker
      RENOVATE_VERSION: "36"
    steps:
    - uses: actions/checkout@v4
    - name: Validate Renovate config
      run: |
        docker run -v "${PWD}:/app" -w /app "docker.io/renovate/renovate:${RENOVATE_VERSION}" renovate-config-validator
    - name: Get token
      uses: tibdex/github-app-token@v2
      id: get_token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}
    - name: Run renovate
      run: |
       docker run \
         -e RENOVATE_REPOSITORIES \
         -e RENOVATE_USERNAME \
         -e RENOVATE_GIT_AUTHOR \
         -e RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS \
         -e RENOVATE_DRY_RUN \
         -e RENOVATE_BASE_BRANCHES \
         -e RENOVATE_TOKEN \
         -e LOG_LEVEL \
         -v /var/run/docker.sock:/var/run/docker.sock \
         -v /usr/libexec/docker/cli-plugins:/usr/libexec/docker/cli-plugins \
         -v /tmp:/tmp \
         -u "1000:$(getent group docker | awk -F: '{print $3}')" \
         "docker.io/renovate/renovate:${RENOVATE_VERSION}"
      env:
        RENOVATE_REPOSITORIES: ${{ github.repository }}
        RENOVATE_USERNAME: "my-own-renovate[bot]"
        RENOVATE_GIT_AUTHOR: "my-own-renovate <131369181+self-hosted-renovate[bot]@users.noreply.github.com>"
        RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: ${{ inputs.RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS || '' }}
        RENOVATE_DRY_RUN: ${{ github.event.pull_request && 'full' || null }}
        RENOVATE_BASE_BRANCHES: ${{ github.head_ref || '' }}
        RENOVATE_TOKEN: ${{ steps.get_token.outputs.token }}
        LOG_LEVEL: ${{ inputs.LOG_LEVEL || 'info' }}
